version: '3.1'

volumes:
  postgres_data_prod: {}
  postgres_backup_prod: {}

services:
  dolo:
    image: loitrinh/django:0.1.0
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=dolo_app
      - POSTGRES_HOST=postgres
    ports:
      - "8000:8000"
    command: /start.sh
  postgres:
    image: loitrinh/postgres:0.1.0
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - postgres_backup_prod:/backups
    environment:
      - POSTGRES_USER=dolo_app
      - POSTGRES_HOST=postgres
  redis:
    image: redis:latest

